# Generated by Django 4.0.5 on 2022-06-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_avi', models.IntegerField()),
                ('assunto_avi', models.CharField(max_length=100)),
                ('data_avi', models.DateField()),
            ],
        ),
    ]
