# Generated by Django 4.0.5 on 2022-06-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comissao', models.IntegerField()),
                ('idCorretor', models.CharField(max_length=100)),
            ],
        ),
    ]
